load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")
mediapipe_aar(
    name = "mp_multi_input_aar",
    calculators = ["//mediapipe/graphs/face_detection:mobile_calculators", "//mediapipe/graphs/face_mesh:mobile_calculators", "//mediapipe/graphs/hand_tracking:mobile_calculators", "//mediapipe/graphs/pose_tracking:upper_body_pose_tracking_gpu_deps", "//hand-gesture-recognition:hand-gesture-recognition-calculator", "//hand-gesture-recognition:custom-landmark-projection-calculator"],
)
